---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: communication

components:
  - ../../components/sops
  - ../../components/repos/app-template

resources:
  - ./namespace.yaml
  #- ./publish-k8s-schemas
