apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-secret
stringData:
  ALERTMANAGER_PUSHOVER_TOKEN: "PLACEHOLDER"
  PUSHOVER_USER_KEY: "PLACEHOLDER"
  HEALTHCHECKS_IO_HEARTBEAT_URL: "PLACEHOLDER"
