---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database-system

components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./mysql-operator
  - ./vernemq
  - ./cnpg
