---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - ./namespace.yaml
  #- ./booklore
  #- ./feishin
  #- ./immich
  - ./plex
  #- ./karakeep
  - ./navidrome
  - ./kavita
  - ./tautulli

components:
  - ../../components/repos/app-template
