---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: app-template
spec:
  url: oci://ghcr.io/bjw-s/app-template
  interval: 15m
  ref:
    tag: 4.6.2

  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
