apiVersion: v1
kind: Secret
metadata:
    name: vernenq-auth-secret
stringData:
    DOCKER_VERNEMQ_USER_ADMIN: ENC[AES256_GCM,data:mN3A85h65y+xn0YLCKbLSobz3gf7EwM=,iv:snTXMQLVJqN7hvoqIM81vwy3ilD0icLJs/KX+5E86BY=,tag:9gjYYzz/rU41AnSvw9WfPg==,type:str]
    DOCKER_VERNEMQ_USER_MQTT: ENC[AES256_GCM,data:KKxWvgZSYJLrqXF9g0/FrWQ=,iv:lZKcGYU0JgOcLp4XBI+HoQyLhHw5zC0JEx+6sfC9M+0=,tag:FNQp94WYCXL6EPK9vnIG0Q==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncEg3QlNCdXJvMlFvUVgx
            RU9jU2E1K3h5dlphWmN4R3VhdXBYaDhybFZFCjJuRjFoZ25RQU53RDhpeElTb1Ba
            RXVYdWFFVFlZT0JmOXRRc3JlWk9zdmcKLS0tIDhFSkJJcytTR1JIZlBIT2ZNZGJ6
            YWxtMWJrd3hUQlQ3dG04TlRWdy9VbzQKNcokkZu9wDTKM17sLcJ7OkafSI1nFhyO
            /IM1vRlkJh12vPFE4351skFkgDdExf4gRoZH9MzXdDSh5b/2YBl8Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T16:47:38Z"
    mac: ENC[AES256_GCM,data:KhU1UOGQgUsVcUecPFxrfOy0jRmtu9F+iWhgsezdFFm37D5dW9nQkdvid0xn8cnvvxyphC3TT7//lBi2LER0kNClhBtPU5zo08hZrqWPD3ox8vPbTQouGILzRfIOjGhReTgrKxyIBX1PpS594Aig1M+VasLuQd+JFoQMNuxCX68=,iv:7xgSeJF5hxZSmwx7sV/6AAUbmMeIA7ekRQ2GXyFeC88=,tag:d1CbYi28V4M/sdPs/h2gbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
