apiVersion: v1
kind: Secret
metadata:
    name: tautulli
stringData:
    TAUTULLI_API_KEY: ENC[AES256_GCM,data:I5kgkO0afYLl7axAVVuXARTooXRddl3B6OwRXyTX7/xSzQuBeex8uw==,iv:rpjAMH+IIC4ZASd16N8Ke5pTqvGEWoSYydC2kEaLlDs=,tag:JYOGFk2NpxSChA/0O90fFQ==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRDRDT2JzZmF2RlcyREg5
            aEgyZ0QwNTJQK2JYbDBrNjRhT3BNSzdFZGlzCndQVloyK1RUU281S1Q2YnI4eXQv
            RVoxa0UxOFNEVkZwQzB3ZUhTNHBMTWcKLS0tIGZLMTZ3YUs3d2FHWVBtczJzdzhp
            dUtWdGJ0cjhjREI5YnVzVDk5VGJJS0kKpa+N5XC8a5/V/eUgqZoosxrio9CJMTYS
            TzhILOHxY59zNtl4Jw7QtIy27jWki4+318WnQ2XGHO5yPUitc1yPuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T13:21:23Z"
    mac: ENC[AES256_GCM,data:BMFYoD+/cDW//YOqo0w70dEcfeAyr8CtVWit6ra61Sj3Gs17XqzWvggHya3J3+S6aSTrzDnBBdE+iw4ydWymLyxy48rDqzy/l2OILHOi0sQoK1UcWsCE066nLzXPe3E/cj2ohgWTU3RuVQC5Hf2AoEXWYC6faZKHuPUbnubi+ss=,iv:IqvIcsFPhngsD39JI9fpXCeAPRrINevMLou4hxHC0h4=,tag:qgGfbBCmdYkJBuIMndcSfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
