apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:K3/o8Lw9tW8wDKT9b5OqY3TSPvY2+fxBgfuZMNGO29aaSh2GGMhjfw==,iv:o7WZR5I/iUlbTIYHnweMQsE+5CO9rEGhpBIRCZ3RkM8=,tag:9frgLKVsMKNIBWBJ1D73iw==,type:str]
    account-id: ENC[AES256_GCM,data:K42H3z1YjydTsLyxlOYV+h+rk9q1rIwc0LYxnZmbUdg=,iv:uL1iK5Ee0/LOgvuEcm47d49BDRu0MjukUrVZtxIDw9k=,tag:UpeTscE5LOZjRnZazx/zNQ==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDL2NaNEZnVlBBbzhGd1Bs
            VmtrOGZzUWRBMVp6QitmQkRLT1JnUVMweVcwCnNMWXRRcVNBWGxBaUNJd2dEbXE2
            cVk0RkJJT20vdHpXdko5c3FKTW5WeTQKLS0tIE4zUVgrWU5sNDBKdTdncTg0T01G
            b3loMlZ3SVV3bmpUMXVIOUVtNDZyNUEKE2TJXJobrURfDlyCWo6qYZFsgJYlvplt
            ArfG9AA9eyodiAMu2F51Yx+KcZqsuYYIdEQ/rqtlF2oOktKZEshe8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T21:33:17Z"
    mac: ENC[AES256_GCM,data:0mpPXLdPLfVROiL0hfkDunaCYnid3i7sDid66tB2uVU69b+WJLsHzFEiC/yxR1BeFfGkGUi+OhfbokFHkvJ1TaZlitYLo4pgRBa+1YxhRmB5/oEUDCN/Ufcn65ggY+GLiV8jbwjeKgk6Auimv6LJzZRY+cJcx60S++07N6443y8=,iv:9ox1GvfEyC0vjw9I6D351e+7q0N2pUueY6KleOd+jGw=,tag:VfL5x/G66qnrz0c9aDR03g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
