apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:WcvJWc2AluvtAWoZCVHvSQvAQhI5RQc=,iv:1WKH9pSBfVi25Hk/k7uRuR2GE4QTcOvIFVOASoo9cD4=,tag:cYmR+p54WBScrA4kDHoj8A==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWTltMFUzY1VZb1pWc2RD
        bWZzTVp6S2F1NVd4c212eHJVOEs0NngxMzBrClo0NFlDM3RQcGNaWHF4dkZFTHg0
        dmJZWFk3c3FrNlR6UGVMUmRIMWVIZzgKLS0tIERBaUovUlZKcStzUzdhRFlKaVI2
        bkUwWVB4Q09haCtuYVQrZm1DZDExcTgKS261rildFFryuhP1kks+YbaWQmD8e++S
        ius1YYddJqQ2WgtKdotV765uSH3ptA1N0ARppqnCKgp8p8Uywu9tcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T00:41:44Z"
  mac: ENC[AES256_GCM,data:ZJ3KIzeFzrMeGGiKpjtmcDbHs2WqRaCQWCufl9yrRMAKHre4BgTNL0+ISu0PcQHOsECswPeH4cioCiuIyzEj9wRyLFTD/+wHpMjdZ62jtyLk7SR+tGL4QoqYEKyc3gwMyrJvpbYzxelNrOIV5L0mubrqkwtgPlvUpKsqbNcHsuE=,iv:IaOntWIKxnytLTTWCqvnF4wwMldNyUzkqjVI8XCxzr4=,tag:vjMnTt57JUxWuzh2ht8z7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
