apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Wp95pxJL/RGvYqSxCwFMVxJn1ejaRIHi+Yf07hri3dqGgnoK3ECGTg==,iv:nVHpG63nOuu+LGFKUtvMdm60B7As0SVSlQUPP+nUadM=,tag:YpEp+KqEN1xj35Pj3pm7nQ==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVnF3Z09xemZIL05xUWZr
        QW0vb2VRMFpid3FubEx5VDhJM1p2SGw3UUhVCkxhZklJQlQzVitMek9WcjBQOHlx
        dGFHVXNaak4zL0owVWRoWlVGS21xencKLS0tIFlEc21pUC9jNWczM2paY0p6bDdQ
        NHVEQktzVFJHVnNPRFFTMVo1QTZHQkUKOPo1tejuoA1vEt1AYsGe9EEwPWHhwpmO
        ECCsjmTyzifmhkfDGu5dGVJmSHSujCet4Zj0aE8IDKN/eTFFReIUdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T16:13:21Z"
  mac: ENC[AES256_GCM,data:vyqlIPoZAXw7cBqUo0LaWOhRinx8B684l3iH0o9YVL5N39MdmyoG+KRoSFlwpRX7YufJEu9GxQtV5AfJmMiY7z1bNVgYKmfsUyQ+2atkWgToljfukSdGw5btqwDe3z/5NVbayq4xWCE/rTgu/jlS5Jeu3emcMhCUU9MspxJ/HCM=,iv:vNl5j74YCKe0exLcjJIcuzV9ilpPVGoGWwxKKUaNOKA=,tag:hnOgMXSB1mh1xEu6dP2Whg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
