apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:F79HLoKG5mqzpXdU9clW8petK6OCeAdK7mXECfYZCjCBrIVgzq8xUA==,iv:Ofwx9/0NvJ+WIiSZSX5KGd/qr0OAXzHJzL0nBSgGCX0=,tag:aWRGgbwUVgpMpOKBNvzDWw==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUXllVjZnYlk0N1RmTkRp
        U2Eralp4bm9DRkluZHcvRlZUcHdXbHMxRTBZClRINzlnd0ozRldDM1VXY2FUUUtO
        aU9hNzRDSGlnTmRWQjJuc3I2YU1QV0kKLS0tIEd4WmExbGdkaEdLQTJGTUpqN3J6
        eDdwRDUzeGVSZWlBRnhrZ2UwWGNvYzQKkk1f371XFA+blq00HWotU31Q43LOMxdb
        2+ERD8pyPiYZvI0mFmEaTFSTp5AHBWAfOmfQ8R+1udY2pqM8MRDVjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T15:15:44Z"
  mac: ENC[AES256_GCM,data:sc5ptbzkuuCLPhpEXtRoanOU2VaA1kJu9FKZ+uRoarhL06Bdk2v+6R+Ule0Zln2NVwPIt9hiPkmxCHpZce48gAHbxIwK6mBma2GgJjUAAo4yd24xnuBgPU5/fsoavdzwFnF5XDKLOS1jbLDZNZ2Nbk+GK1Q9cHFp3cwkCSipxsw=,iv:8E0nSI+nn75NlDFklQ3xpeOhFDGcqf4r/q/LGi0zMzY=,tag:9nam0padd3spfLEvXDFjKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
