apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:kSUSdGQHICSiAi8nvaDgEFzL/VGcYve8P/Si2yGSHFIo3oPHQdAWUjWmWbIQZZw=,iv:Chv1ovIfdTd+MaQHwuihr3y8cubAOr80Fjfkdl+thFA=,tag:W8h4L7X/WYaLpXIpSvAbpg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:DYOgxKL/isykzUPQeroucni999HArY8kp/2l6Fq2RLuI8LJRqTd0q/6qCeEe1G0=,iv:VPc1BW8q8yMnjOpL9ys0TloxeE12YL4IK0QdUhXyP8w=,tag:MlYI3TIDlSIOtgaP6k0myg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DQ4XP510iouZxHk1quzldRyxQnxerhSBj2M=,iv:HQIIDDLhgMUd/FVk9GLE+Mr7NzPVlLbng1uV8zc/ZHE=,tag:1bNVkRplUbQ0cu+tA7GakA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RB2Du0GVSyoBXIrLbc5Lqa5XJPRdgyLDp0LaOR1KiX8Fsu6Y18mZVrHuGJSMyUkvtkiw1r6WM7i6krnwJHmZmA==,iv:5SoDONSzqq3er07sJUNH0xvZ07jdvl9zxj+BIoZD2D4=,tag:OqOe20odWaS7CFcFWmjxyw==,type:str]
  RESTIC_REGION: ENC[AES256_GCM,data:o+eeADK8,iv:gD2rpiv48Wz9iHa7rJtHkMuaj60mti+eld5sKT49HTU=,tag:Xo3LuVe090x80l/zSax/2Q==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRDRDT2JzZmF2RlcyREg5
        aEgyZ0QwNTJQK2JYbDBrNjRhT3BNSzdFZGlzCndQVloyK1RUU281S1Q2YnI4eXQv
        RVoxa0UxOFNEVkZwQzB3ZUhTNHBMTWcKLS0tIGZLMTZ3YUs3d2FHWVBtczJzdzhp
        dUtWdGJ0cjhjREI5YnVzVDk5VGJJS0kKpa+N5XC8a5/V/eUgqZoosxrio9CJMTYS
        TzhILOHxY59zNtl4Jw7QtIy27jWki4+318WnQ2XGHO5yPUitc1yPuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-26T16:26:22Z"
  mac: ENC[AES256_GCM,data:JRZiUR33UzAJWoC5ac/5V4V73nij3m5N9jFsoPO7wgOKNKFlysfMz2KGBKCLn747OezA3vFsWm5KD+XyQVVAI+L8nZwx6AYKPnC4+DwTxaWarJwTXIZOCrh9hzBZKJ9eYrzrXmtEEKnRIdASkYdzixnaBxl1uRTSPhlO3jXCxL0=,iv:Pg8Cv/9HdMI7gw9MrF94ubJCBVdbyVmx+Pk355b66Mk=,tag:9S2Pw4CFnWQoAS4enip+gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
