apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:kSUSdGQHICSiAi8nvaDgEFzL/VGcYve8P/Si2yGSHFIo3oPHQdAWUjWmWbIQZZw=,iv:Chv1ovIfdTd+MaQHwuihr3y8cubAOr80Fjfkdl+thFA=,tag:W8h4L7X/WYaLpXIpSvAbpg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:DYOgxKL/isykzUPQeroucni999HArY8kp/2l6Fq2RLuI8LJRqTd0q/6qCeEe1G0=,iv:VPc1BW8q8yMnjOpL9ys0TloxeE12YL4IK0QdUhXyP8w=,tag:MlYI3TIDlSIOtgaP6k0myg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DQ4XP510iouZxHk1quzldRyxQnxerhSBj2M=,iv:HQIIDDLhgMUd/FVk9GLE+Mr7NzPVlLbng1uV8zc/ZHE=,tag:1bNVkRplUbQ0cu+tA7GakA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RB2Du0GVSyoBXIrLbc5Lqa5XJPRdgyLDp0LaOR1KiX8Fsu6Y18mZVrHuGJSMyUkvtkiw1r6WM7i6krnwJHmZmA==,iv:5SoDONSzqq3er07sJUNH0xvZ07jdvl9zxj+BIoZD2D4=,tag:OqOe20odWaS7CFcFWmjxyw==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRDRDT2JzZmF2RlcyREg5
        aEgyZ0QwNTJQK2JYbDBrNjRhT3BNSzdFZGlzCndQVloyK1RUU281S1Q2YnI4eXQv
        RVoxa0UxOFNEVkZwQzB3ZUhTNHBMTWcKLS0tIGZLMTZ3YUs3d2FHWVBtczJzdzhp
        dUtWdGJ0cjhjREI5YnVzVDk5VGJJS0kKpa+N5XC8a5/V/eUgqZoosxrio9CJMTYS
        TzhILOHxY59zNtl4Jw7QtIy27jWki4+318WnQ2XGHO5yPUitc1yPuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-26T16:22:07Z"
  mac: ENC[AES256_GCM,data:w8PH9yKe301YhWxiSEIQbiHQIuOwspRFpCA2Pq9sg7hMRqPsEz+tt566MX7AlxdYuyt0gXI+NJQUnWfTHcfquu11eLFCpaMOuj05ezQOTUtme83hzrsN0IXYwT9CCH4ZXlRjCg7gQSoF5NnZXubCQYWE0AnbN+WzSPA7hexP1yg=,iv:qX6rfhG6RkzmSo80vPXp57wVU7O+HuajxQBEJpc9NfM=,tag:GY0clmNi1n2rn9fU/i1Uwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
