apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:erg4A+k0cpmZRV0g,iv:cADASJgAXHrmSUa0igY201JHWMIiQIi3NRrSqDUVAX4=,tag:/arIU4nNFZMv6/Efc7iFGw==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRDRDT2JzZmF2RlcyREg5
        aEgyZ0QwNTJQK2JYbDBrNjRhT3BNSzdFZGlzCndQVloyK1RUU281S1Q2YnI4eXQv
        RVoxa0UxOFNEVkZwQzB3ZUhTNHBMTWcKLS0tIGZLMTZ3YUs3d2FHWVBtczJzdzhp
        dUtWdGJ0cjhjREI5YnVzVDk5VGJJS0kKpa+N5XC8a5/V/eUgqZoosxrio9CJMTYS
        TzhILOHxY59zNtl4Jw7QtIy27jWki4+318WnQ2XGHO5yPUitc1yPuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T19:13:05Z"
  mac: ENC[AES256_GCM,data:5zxlZIgRyE0UaTWb1hoxk8vzSt9tTfmzgFLXlnGRaFZIN8HVrsP7JsGGmrAA1uUwAdTuIqNI8MgRU0DOyaiIQ3uueatLK5vNF+TBz3rYrP/dg5iMxciKmlymRG29CGKtTI1V8RzNNHkwAwpQSq4hoj+MM/m0UWGp4tLqpsNogMo=,iv:OrTY43heyb6N5aeW1727r1EDLlKSIwhNfWO+fOwFhEY=,tag:dYuOop+tWdr0eLmcqNv7nQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
