apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:khL1/g7yP8QmyQ4y,iv:fYCiVxr8D0XYPirwR5IfOEXUVMNr2ZhAhs5/fRcMVi4=,tag:lmUAxJjPPogizMYZrd0V0w==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvK01xN2NVSHVuRDA1T2gz
        K2c2NTEzRHJqUDRiS0RWbHRuQXF0NmpEQkZFCjVQOFYrbkQ3SDErM3JzZGw4UEkv
        cWpraUw2Nms0VTRLYXZCRlFSbmRzR1EKLS0tIGZkK0VQYng5UC9pWkxYc1JaTnV1
        RWVIOUVUd1J4eVpzWXhEVG9GZ01wdkEKwO2dNlcMdP4Q4BbKQpwQ7hxh9wc4MSJ3
        +BscZHxqDJTUwSI3RUNPA1kZ1J9Wiw3Q8gkZ9vdtVlqDIoNKGnI8/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T16:13:21Z"
  mac: ENC[AES256_GCM,data:SzH4m0t9NRPcdWjQb/RCz2tQsSpZCJwcMYGm0WMY8QjaOSletnGHSyaVn9iK1ZMZpFWoKrv2utqcf8DP5QpW7JSnQdV2kN76aGF0kOMDuq95XscuobevqussAQGHkGmfl8joBJoPf7cFKwflBhLoHwyjgqEWDq1JtQyqTPhvBJE=,iv:BqIY5ePbDSOu0hL2QJCd/Y166JCl8X2S/pi9W4mBc8E=,tag:nxsQB0c7Zmjd6JJqOKcoJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
