apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KQEracerlc4Kmx36,iv:SvLItsXBxWcIXvS5AYiOd8oamWHWaL4vZkbDpzvpcB4=,tag:y+aVrJKg1IFolZwTTO6c6w==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV3hUWlFzV2JWUkU5NXhp
        MkhFOGNSWWRRVUhjY0plQzF2UlBRTm43aUZVCmpxQy8zQy9ZQXI0a21LMk5CUm1V
        Mjl6dXBULzVyRUtMdW1maHRFU2IzZW8KLS0tIDRWditxT0c3Z0U1dW9WcXp5bklB
        ak92UnduNHA0ejBnMzk3bGNsVlp1NVEKVRqkajR4bHxA/0m1N6YjldpldNBpcz3j
        sWWU4xvRglybf4EHF7iimWj7NGmANMFGDWE6jluT5JS1+ptajovT1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T15:15:44Z"
  mac: ENC[AES256_GCM,data:MKb2683b0l3ngTcY8eaK0o+hfw5CX4D3HMGiVjkLp823rF9uk7qbv3d/GmA/Q5noNIC74dp5/UHDRC9b3xBHMQofHHLh1I9QMfhQv/2TErZ80VDTlMVu6T7Sl/XuAokSW1mQ05kDMmq7AJ1g48JwSu16KMUNtzcuveL6r/Vu/Rk=,iv:GFD3SlCX5etgIhWJHnSfRxE8r0eJfECSXcRM/1Ejopc=,tag:0uyjBji4hf1BttEprs5zHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
