apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:8zu1WoVNAIYIOgpP,iv:xqaUWgoGqm9aPiVl7DtOpzWfecEDrTg/UZp2FM47FM4=,tag:Zt42iFk9jtj4aZcfo3ssnw==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Nzc5aWljcEM3ak9FK3c5
        ZU9sK3VhTjZZNTBKQ1ZRdUZEM1g1MmVwb3dZCjFnSi9ISDRSYnRNOWh2anVZN3Z6
        QzhXSVR5b0tKMkFwOEhvRmEwZ0o0UnMKLS0tIFpyS0paWEpqNTQ4NWR6bUZoYklM
        cE5Bb28wTThSZ00zNC9xazdvMTcwd3cKI8Am278zmY2BG5EqEKtVmpp/+ONrYMwt
        GsFfU512VdI9crWgVhSrX3uyD+tmEQrL+YywqpOlOvx/KeANYzjhCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T15:11:58Z"
  mac: ENC[AES256_GCM,data:7+MlxiwapEYZDUANip+m8/jZTz9aKh8KHhJMXZbD/C4M2ZS8oe5Vkhf9iTDM1ok378s15Prucjg1x4CtmhsvJQeQtOeT0kvCews0KAerknWXW9nQOM+faL+PV6MelUGrA/6UzxgtRAHcQF159fvfCpprBzJjoCe3vFL6XOAu3+0=,iv:preefTi9qilhq3e4HtNFqALLFMVnwtGoSK6K4PCROV0=,tag:DtckcjV3nune5pnOaJrnxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
