---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: infisical
    app.kubernetes.io/name: infisical
    app.kubernetes.io/part-of: infisical
  name: infisical
spec:
  hostnames:
    - infisical.laurivan.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: infisical-frontend
          port: 80
