apiVersion: v1
kind: Secret
metadata:
    name: infisical-secret
type: Opaque
stringData:
    encryptionKey: ENC[AES256_GCM,data:cNaAqCxdQE5meUoml4R8Ii5tztvmSJJ2td9StVTDHKE=,iv:6rPAL5kXj6V9NrVVSmjpflClZl4UlViH3Tz5mwDbX1o=,tag:5F9fLW6luASQl4+JKLxjew==,type:str]
    authSecret: ENC[AES256_GCM,data:3hADiy5vLh9uo74jGuqdTgynuqsrBMAtwvcbbPCg86A=,iv:NlP1kvKZd3EdJ0m3s/TMr0+rDSS1GU3DchZqBM7vm/Y=,tag:YpcRppitTtZhGruW7qQE9w==,type:str]
    dbPassword: ENC[AES256_GCM,data:22uf5hnP+E+DvKvW3PvtcR7WRNcoJTifJOkq5aug97k=,iv:29mY7o4tAs4zkREJS5JwIQnUQmNJ5iHfFGEWMN8R43M=,tag:tgDrF6aWeMbIjkETlf0B8g==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvK2NQczMxUy9PME5IN2Er
            Q0hQNGxZQjBBeDBRT2ZiOG5FVHhHRFl0Wkc0CkRyL2JVcDJUbk9YZmNKaW14N1lu
            UGUreXlCMTVTRjZJT0U5c1dMd3FtNlEKLS0tIG4xclFDeGEwOW14RWJvSVJacUk3
            dkk2SHpZNzd1UzRWR3cwZ1RjbGluaHcK8aIyAZ5t/vdYcQcF3QHLQ2XPPKJv6QjJ
            XsJ/hWxJW7bwlL3/LHhBfJBBqd/RDFQ4GooQkZ/YWsK3MnV9P8l5/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T18:00:21Z"
    mac: ENC[AES256_GCM,data:95O/ulpjlExnMXa1I/K02UzJXYpQd8SxbeNUTfOiAEbAI2DRKaHs5QDybsCDxJza5izGJJN1g8S299WlunxYeoB66FNn2YcyeySDohpG4eqLwX9ivDUscsv1nyK1/fa3BrkedT8hz1klAyaig4WwnyhjHcjxT8lMNN/v2WkPAWU=,iv:kgCOh7Be5ImdlUn3PhXjgPXGG2vyvRVeO+Qi2Aoytk8=,tag:bPb182wTMQVV9vODLT//YQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
