apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:tLNHubXDxl1N78+Xbvx5MnjkwmunVmkSx5PJfDFI3lM=,iv:FrBOejFWHlw+/e36xhubNNVaL7CzF80VBZAs3mdRsfo=,tag:OWsTo+s5s0mnVyJYgAIRsA==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZWtUdEF2dmlHNjN6MGND
        N056RUU0QlNrR1lncTNSSkhMUGtHMFF5Sms0Cjl3TWVrZ3JyakhDQ0IzcHpFcVNq
        SGZQZ2dDSlcwWkVYY3JrWjFFRnVFR1kKLS0tIFNldFhQNTBJME4xclZUOElDYUVu
        akQ1cXFzR3UvMEsvRFBEVlREWmdZd2MK66s7WhNU8Nzw57JX8VSVfQj5ZLRLYFWu
        KelG/NMpGRiMm5nNcriAjNas1IpGB6C19qMA/V0k/UPcxZYla5MvqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T15:11:58Z"
  mac: ENC[AES256_GCM,data:uneVTP2R42tjVtzZhTF85YUDw38uOzHmnBxP/VctwEGFHoZkAEqQmNo2pZOHgfLFdMMKYJYTx6E6WqBDnU5YS/5DxfOZyQa/zhfYVWddL1do42tOAwfM89KgLx2rtxWOV3Ztimb6ZAM8zPnUuuGgMJX7GLetoqOxJLa4frZLKnk=,iv:2RH6X6dgSOXPRHWiHgmJGyY4HdepDoVtKRu/c1Aex4E=,tag:0wdRlHAxJg2rE2oR3M+vpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
