apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:RiZ7Z1A8GHbknZr4jIdo+LHKh6H/MMNvHWlhaLspLWwJskBhpTS3yw==,iv:5qQUOiSEhgZV7n85t14VDKYTCKnqaggu++mEIEelcZ8=,tag:chiBOVRfmp72kRWH1PkrGg==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZGVPWU5Qa3RPaWxSc2E5
        UE5uWVNwYmlzUlhSUjJDbUNtRm1HVHNUMDJrCmVtREZXV1RldC96T2Yza1dnQVFN
        OTNLaVpzbWViUE1vTm5hRDNRcnBWZ2cKLS0tIFhLb1VVU1owSithUlNKVWRYODJm
        WGRxdSt0Y0d1OVY2bkJHbHJXdUZKcGMK0VZSsEF2rBIF3NtHPoQCnmQkVgyZ3/j3
        SsUAbGzxFKBBDAuqFrUYamUwi1gkVAXqymUkUyNyiWUrHSkg8fZ4yA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T15:15:44Z"
  mac: ENC[AES256_GCM,data:w8TK6G/GF7j0jae2wuSUIX6g3wgkG4yr8wfcktuvFTANFFuIsbcM4cKnssTTSgeafZ2g2NKHgwev44Wf+VdLNWg3EJDbmyhtWpFRuEqB6781DoxtAsjx+xgoWViIB4iB9Bvf56o4xmwdM6fEZrzWCG6leHC+/UmSgd5FH4mzCpk=,iv:mdB61g/U9FWX6x0PvvdOdfbAlEpw8L7lno3EOr8ifNA=,tag:8QiZYzr2PtUHgEs3K99RUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
