apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:P+zAT/mQX8C0jU/hGldhlKqVa2NnxUEgcWFuGLglNJhAI6JHmVl53A==,iv:GHDWYYE07KkozqiIrXF+HI++2OY2YVBmJLpdsTU2LSw=,tag:LQEkKJhirxclTuX25zfQbw==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSzI0cld6Wk5xUVNOTFA2
        dG1XS0VpQmp3L0QrLy9FWDE4OHozS1luR0dFClVJa01kaVZPdURaWkg1Q1VpK0w0
        MXRwR1d2Y0VNNDF4MWVaTkt2M2tGMzgKLS0tIElvVGh5SFNVUG53VmdGb1pYbUNF
        ZGpGMm1aV25zeC9RWi9iQVVGRDdIZDAKvFIHebgjop6cbtxwDW6ikzPF5qohWlvg
        zsojWBZdZzQt2C+g9y6zZ9ZCGa3ISbTQUhtsH8MUQjze9Vb1/zwMTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T16:13:21Z"
  mac: ENC[AES256_GCM,data:JqrIUhchinSPIHgTr37AOk1F+kN9h6F7XyTFHRUYVuflmhksdlXP7NRvKE0snMoXBngIsmstLC1Ei/jz4u4dckgxkwWOPfjZpGHYF37z3xpgkWCSPNLlq1a0byxYtzd9jpV7zF4nMZsx5+wnvFs9yQtWcQqyjCqS5iUUul0R9mc=,iv:fylzT9VkNfNSSB1XQruoDNCCuJCYK5SFOYKhg51F7ao=,tag:IIWXnzD9DblDDwnC576R6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
