apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:vh8V0N/o/+2wX4K5UtxNPvDhbIVIbrdWF3EOy+/OXIXeGEfyKiUL/w==,iv:/C2J9W3gkcesqyjmGeFeKyzlwHAxVsoVFgvBtfG9pLY=,tag:zr4vL4VhUN1nVNc6thGayQ==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbWZRUUVndGc1eXVLek0z
            Z296TERSbmFNNWkwWnFadmdQNThHUkpkS1UwCjVIODkrT1o4VkdpR0IwREdkeHdz
            L0VQQU5IampERkFUa0M4T05WYVQ1YkUKLS0tIGJ2RWR1aStqM0M1bHdFcWx2bW8r
            M2ZwTk1iVVh2dE1VeGFzb3pPeHNZbEkKVPjAXOwEAxmBTkE+NB4yfgCLxZyjqXXu
            n+wvczrZRbjAX2a/+PS5cTzXx3tiJu8JtvJgufGmGpeGnrwa83PkeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T15:13:21Z"
    mac: ENC[AES256_GCM,data:i0Qk35+36hU0+NJbpxST5ytboJ4WBOM7GsppmSdlqI/38+OO2ZqbNa/+iYd5gSSGa3deshIHsQJCO/NcAdRf+iQJrhJb0pM3SGwCf0UoCwHIorzbN9JGm0Tz6V6pXUzdwliRgQN9PbJfSyo+Gnm2/MHWsC//EVgEKlXh7RujDjI=,iv:DJHCUodoXgmZq7FffprBWpRYL+i1JkceHin5dspiP2M=,tag:QZ7a8N038xDVoecYCmWLNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
