apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Izz95QiCRTxans5ogPlELMBW8mS1MxdIdKNemTmJn0w=,iv:vTgx9nMQvDYdfC8fPsfHMgPoCt8vdEmrs4xUwvZC200=,tag:zD4qZrn1yREXXvQ4g5jjjA==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZmR3b1ZaL0JKVzlBVTg1
        eWlOSnpNYkNBUlYxelMwU3hJU1RTUjF5SDF3CmhWVGlGMnJ4bzFhVk1CVGt5SjIw
        U1d3cXRvTUhyaFFnSXhaWStyM1dCdlkKLS0tIEIvbEY3WldlSkc4TkNOYXQyeXl1
        emd4WXF1MnBOTlY5ODFiamMwOHgxc0UKVPa/FP9/ZbuqFHIfl4mj1KIoadL5XK81
        pVph+eEOb/A5lBCtQxuuAu7nNOIbT9RBIGVjBADq28MwYKPoiWWXiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T00:41:44Z"
  mac: ENC[AES256_GCM,data:2EzDzs9CfeWb+T6INQSXRdvslL+NTVgk+Xy0JZYtLH+lV4wH2BdEwKIELEcJCVdQXzwt6INJK+BW1avs02jH9bwB9smmeOttPFsfpc7xS9REafPUsvZerezZh9Nn4yUPeQvq74sKOYviaRHGmMtv0D5EfBil3qU9czDQ7I+Kf7c=,iv:epLU37sX7HBfEaIgYXpocMed1HXP8jVvrxcY7bIYh8M=,tag:ImZ4tZr+Zgfre/SZMz6n4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
