apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:8kPnMTKnqB5DVVAGUMvzfXhRG8mcB2oCHfBh582RbUfCegmoMHDd2g==,iv:QYeqn+lxMAFapk/lUDxwMrmuZQosANfeSJuxY3hQssI=,tag:oVTRIKea99Cidi5IGPQ9tg==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbWZRUUVndGc1eXVLek0z
        Z296TERSbmFNNWkwWnFadmdQNThHUkpkS1UwCjVIODkrT1o4VkdpR0IwREdkeHdz
        L0VQQU5IampERkFUa0M4T05WYVQ1YkUKLS0tIGJ2RWR1aStqM0M1bHdFcWx2bW8r
        M2ZwTk1iVVh2dE1VeGFzb3pPeHNZbEkKVPjAXOwEAxmBTkE+NB4yfgCLxZyjqXXu
        n+wvczrZRbjAX2a/+PS5cTzXx3tiJu8JtvJgufGmGpeGnrwa83PkeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T19:13:05Z"
  mac: ENC[AES256_GCM,data:pe4qDvYhEhNVI/MslkNhC60Tq2/YqmmEIxXGF0KlLcTuKYGQLeaYnI0fGrAKugL6x02ZSREID0s0Xi/SejDLMLC00RCz5GdNPjuDmQljnIAorUpI98s2T8fq60Nl+P+DeTFbO0BZ0exwEPA8lnWV7galhbdVWpBU4zZlAHhYnCk=,iv:C0vKzAR412Ql+RrZK034fnP3/ElwDychrpWNbh0bVSs=,tag:hrejmMUD6E0VU1wNXLKhjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
