apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    #ENC[AES256_GCM,data:IvhoPyXVw75X8pU=,iv:1CWSPac9y9lBeLmxmHnrHeWFkAutYQXrQjtQEI8uEow=,tag:iOvsj3n1i757mnNDkL9sGA==,type:comment]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:AznP+gnoEuJsyodnOT87BljKB/AbRnAluLZbdRcOqTN3jclA798=,iv:v3FD0nV6rUn1Vfn4lYYOMysre++6fnABj7SS/OyQxo8=,tag:/aSw3Hss8jW7+sFuhBpsIA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:MQ3boqCQCc2U0RM=,iv:SlWxpl9qIedoT19h6NJgW1d6fx10oOKYqL6kSOlpEvQ=,tag:cG263Z6TVDrUEab8/4eC9Q==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:fLBNRkxOaD1hIcU=,iv:VY1XXFeGsVU5VXf+Qco1MFkNNOgsmXcztvak28bld4Q=,tag:xDC6h7gUMeef0s7h0+Y9bw==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRDRDT2JzZmF2RlcyREg5
            aEgyZ0QwNTJQK2JYbDBrNjRhT3BNSzdFZGlzCndQVloyK1RUU281S1Q2YnI4eXQv
            RVoxa0UxOFNEVkZwQzB3ZUhTNHBMTWcKLS0tIGZLMTZ3YUs3d2FHWVBtczJzdzhp
            dUtWdGJ0cjhjREI5YnVzVDk5VGJJS0kKpa+N5XC8a5/V/eUgqZoosxrio9CJMTYS
            TzhILOHxY59zNtl4Jw7QtIy27jWki4+318WnQ2XGHO5yPUitc1yPuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T01:19:11Z"
    mac: ENC[AES256_GCM,data:GnylKsWOeGErWoijlKHPVO1MZDfY4CphgtqDX7xOH0mZp25v5QcDy78BQGVeB6TXRDiMVWNbVJZRkfdgoEGsJK7x1vnllV86EDwjB/HOt3yXBnA8dXvDdO1ZEnmQVkxjy0odhb5UO2QDctd+E8dYTdbSmh1M/DA2xEqAd326D0s=,iv:JCspZC+Yjv+9Ae8lRb1kN0Dj5uwaegLNjGzWgjWJI28=,tag:KAYQTl+ECMmQxl3UNtk19g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
