apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    AUTHENTIK_REDIS__DB: ENC[AES256_GCM,data:NQ==,iv:dvIMcFn9YX+zYG41U/88S/yLoNvkyFDWs7/beRhGm4U=,tag:0U2IDBiVR55kaiNWTL/dXg==,type:str]
    #ENC[AES256_GCM,data:3mfEoXilr3LgmMJUdI6sQwPIp5U=,iv:MKaPFXhpw8Jzx5W4nSAV+leHQLP9eTDm+U4XG0UgSt4=,tag:wUDAEPXEI8+Th2RdrMG82Q==,type:comment]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:QuGa/VoJEah4sPV7/cp9FOErkg==,iv:f9wtoFk49c5tWY0kOYIJ/X8y/sjNQK3kYwMJdWvzX9Q=,tag:cv084FTD5WT19VOWnWWhfw==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:9dXOcVEaEaRa+unFUNxE7h4=,iv:/9eze5Jf4PlgiRMUwt4xXeVNXH6QthNMtnWe9vfEwoQ=,tag:OKywbqdny7/4R9RPq7QCSg==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:DDl02SdXXiLbZx4Kdz6Sq/JjsYCr7lk4Bg==,iv:G/AYxPLdWfgxHbM7/Eyh8Dee2XOusJHnPbgVspki5Ss=,tag:NxtkZ7W7mUb65/EQrm7TsA==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:tg1hkJFW6EE+Pdowco2+Ip4YRCqLlidzi0ELZm6c6v83O3Q2xTuolw==,iv:QgY1epjG1vZV8YgQ4b+xd17qog3Mawk8WYLk5fWcuzk=,tag:kyn41BLgPFX5YlbZYGA2JQ==,type:str]
    EMAIL_SERVER: ENC[AES256_GCM,data:zdvCHXaUwY7v2hHMSHs=,iv:ocjqY+n9i1ET85aYZW99TrzQf4PkaCC5Qr8SHPSV8Cg=,tag:FXGTmJu9jGUnYe+7rKICkw==,type:str]
    EMAIL_USER: ENC[AES256_GCM,data:JyJel6AdW/RaqpFYMRaHun12rg==,iv:bnqBIKF2ENZKGZghW2+54Ct63TJHu6KCz8MCH5n7B5w=,tag:4m4EjCHPxo9toeIIrxgy8Q==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:qWaXN6cnNOYMZQ7COoLoF6X7f1Vrp2XaxdMSCwOB6g==,iv:uMYK/Ioq14si+W5JX5RxUkcNkAeMejY4Efk6g0cPh34=,tag:Z+2wmmwu9lKPAJXkkLDmfw==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:g3PQzzmHYPVQmT0Qy/MnEx+IKg==,iv:imWv03wlwSZXyZTqCOs39TinnaHW7LDsViDFi0mSTyc=,tag:L6yIeGf2pibWzQ/6Ym2b8g==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncEg3QlNCdXJvMlFvUVgx
            RU9jU2E1K3h5dlphWmN4R3VhdXBYaDhybFZFCjJuRjFoZ25RQU53RDhpeElTb1Ba
            RXVYdWFFVFlZT0JmOXRRc3JlWk9zdmcKLS0tIDhFSkJJcytTR1JIZlBIT2ZNZGJ6
            YWxtMWJrd3hUQlQ3dG04TlRWdy9VbzQKNcokkZu9wDTKM17sLcJ7OkafSI1nFhyO
            /IM1vRlkJh12vPFE4351skFkgDdExf4gRoZH9MzXdDSh5b/2YBl8Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T17:12:02Z"
    mac: ENC[AES256_GCM,data:elJW8UF7uolPm7EoKoaIaqDhoEwfBT8GHc1zzsH9IKvC2V6dhrvEkRFrRjoNinx1NZD8ThXrTEL1QXwyUKOBk2CvqIda44CoXxdxfHQJpC0k1HUt69IX+dXh6215noGj5O5Q0QBadyn3/0PKudHv8geqayOD+vFrOaKdte/r/Iw=,iv:dRBP+sov3pM9gQbIrlSJDdybATnBw3jbj+3Ub+V3jxo=,tag:owPqjt7j11huT9kSLtcF3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
