apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
stringData:
    rootUser: ENC[AES256_GCM,data:Z5eHWPs=,iv:KYdW7Ysg+n0yE0DpyTEla7ClpFXSe5yZoaffeLndBDU=,tag:F+cfs2hWo4NwpkAEsPs7gw==,type:str]
    rootPassword: ENC[AES256_GCM,data:+/AqFPtyhC7dYEV/xFrcRYY1lw==,iv:vzi0RC2kvQrI9uK8a2Dv6RmSRrBPXjfSO8hCoJVbEFg=,tag:+Q/qbkJGsYlzsuPE8rsS0A==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncEg3QlNCdXJvMlFvUVgx
            RU9jU2E1K3h5dlphWmN4R3VhdXBYaDhybFZFCjJuRjFoZ25RQU53RDhpeElTb1Ba
            RXVYdWFFVFlZT0JmOXRRc3JlWk9zdmcKLS0tIDhFSkJJcytTR1JIZlBIT2ZNZGJ6
            YWxtMWJrd3hUQlQ3dG04TlRWdy9VbzQKNcokkZu9wDTKM17sLcJ7OkafSI1nFhyO
            /IM1vRlkJh12vPFE4351skFkgDdExf4gRoZH9MzXdDSh5b/2YBl8Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T01:36:30Z"
    mac: ENC[AES256_GCM,data:gScc0LfX2vkQ0mywISwFHLC6Mf8822knzSMkM31QQI58hPfctH1JJ1sOC6f7v5ubNONUrhUOxRUjOkEp0cHB/IGeSj+bC/jbFFR5et8BN6RWRO3P/FZmtSOLgLe/ydGCO1zqqXHbZWbUZ3sR6bBJfpRCPpmFTf59WFfyQj2P+1o=,iv:5Etf8hUeVRRJuy1gpbcxf8uPHjYvsoMEOomhp5vAwWM=,tag:NyYUcaERK7vrBUySGHb+Hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
