---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tuppr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ServiceAccount
              name: tuppr-talosconfig
            patch: |
              - op: replace
                path: /apiVersion
                value: v1
  values:
    replicaCount: 2
    monitoring:
      serviceMonitor:
        enabled: true
