---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tuppr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ServiceAccount
              name: tuppr-talosconfig
            patch: |
              - op: replace
                path: /apiVersion
                value: v1
          - target:
              kind: Deployment
              name: tuppr
            patch: |
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: home-nonroot
                  emptyDir: {}
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: home-nonroot
                  mountPath: /home/nonroot
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: TALOSCONFIG
                  value: /var/run/secrets/talos.dev/talosconfig
  values:
    replicaCount: 2
    monitoring:
      serviceMonitor:
        enabled: true
