apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:syjBrBTRKtixZTytObYGKJOJctZcCGXz3zH814fUn7iJOGR7X/W73JaPTPQz+FCnCCnrg//hbrgKiuayWJo0KjIy8/Z7oWWeGpkdVZQTxBJoS68M0W4X9bv0h5cz6OS5g4Pnx9nkY0U+BVvg1sKQ6/35oYi3O8OFi9+nuHQNaQbKK0Jc/GNuqMHc3C2YWj1dBHQgplVVEO/81k9h9bPGtK61G4QZJIgtnQvCJ3oOv23i2/uV,iv:uXiebkh8o9Ma8SMD7EMUJcDvMaUpso8FDplsE80RljY=,tag:21lL3z7jtYVaJWB2dnlYdQ==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcnZsN0lQOEp5T2JHUXZG
        bGo4KzNvNzBxTWlXSXhNTFlkNVdUZ2FQcmtvCmpnQ1hZN0REbHVOeHZWRlFrRTU0
        UjR1Y2p1RG44Y3creTNqSHVQT0V4TTAKLS0tIHpWaEVqS1h4WG9pUXRYMXRmcHB1
        YWgrNjkzb1RvdFpEK0ozYjNmeDF3OEkKnpjJD0fcR2UmCj8MYsC2SLIwhXo6dFWs
        d92slhnijEVrVIxNuEvd8PBr+V3otPhVcMW+fqYWbmoPySEdD3CRqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T00:41:44Z"
  mac: ENC[AES256_GCM,data:9ho0CklKYBA3ynca+tcCMb/LULWj8EIN4pMPllWGFS6T/ESbZgWyMSQcPE1gdVGXC13vLatc7jSIkjjsoFPRfJ6BIgGsuyJv7tLGfLXBHj8+6fuRRDT6dItB0+jrIhq1jekS1KwDaKbzKmFDZN81/nv6z6Y+SyKcOkVfOrZWrBk=,iv:AFyDvL0bczXw7qYgsLam6sgOYf7hCLSyc0HegApLG/Y=,tag:WaEiOxU8r2W0hHwXtWqfIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
