apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:v4eVEbH5eQfjylAUgAeaFgoZkcKR70VqRuic3wZRphGiw1hjYn55K3iaeICnFkk/vc8lV1SPnE6tsc9Ankw9ufJoyPkIxHPTsLGpS5LufDYAFNuFdmc5f/pRGoH5Tt6OEK5nQfwUIzjgVq5x6pzSChuxYD9hMyKhXmc5GGdc0zBdQ2ggu+2LIatnwUotClUXGac8keLxI9QIjKIw1aL4oshQ9HtB020KdxstXugPVhjcrxYc,iv:+c10CxVCma+JbkJRW+eojx8PDqE2DaOJDl9nJAOBIzg=,tag:8lHp2g/QJhOA5yX2Jkf+jA==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGd1p0MFdvV2V1UVQvRUhQ
        YXhmTHBKaG51L1k0blUxaXFCQnRVVGZ0QXdjCmdwZHBXeE40VWh6MldFTThxaXZh
        RzJsc0prbVlWbWdBdWthZXAyaExMTUEKLS0tIG82TkdXWW91ZGh4L2pRUWs0ZE1Q
        VjYxUnJ4aU5JZ0ZJZW9QNlYvK2J2OEUKJiqjtnKRTvpI610vMVXAakQOEXXIPvsX
        o2G+h78hADmXrsmHutCAApX8Ld+Oj92BanJG4xujhwmlRqEyVD7aVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T19:13:05Z"
  mac: ENC[AES256_GCM,data:Q6ZJrHMe/31Tw9N16PUKrfFrVo6ESi06HPdYyFymQmSInA0VI5vE4KHcupXK16OD3FeC1TYXfB/MhsgJ1X3ZxBwMjCdAD0hApBr2ybrwaEGRb3sb7jZIWd6qgYkbVURJviDkErhQ58tIWBbVc4Pm9DKcv+hRyNX2Q0+4wReAYg0=,iv:CPl6uNtURHA/wPd96jaKOT/3F3Ku9I5aEQUSYeneFRs=,tag:/TVxFkk1qvHIpxnhk6UQHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
