apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:2KFqQ4rwAjvL7hWPwwI3lVqzEY67xnCMCI8MBaGzqT7uP6eBrEmp8M3f0Uow1Px/hSuTMLh2wTJ1BSH/Ypm2OfkbEUTO9LEQ3r9pfERji4y7h17PoSl73/Nf0lSXzqZc9ICT9mA5a9yVzIX68S/LKsFQ8Z43EihC2ae8Q/6FjwCnmLrdwGB8KGesrIqpsiA6M4QgtAYKiRLv28qXUltUSYv3h64WqjkmNwLKmteiaLGi7wqy,iv:8Smo/SBR1rDQqaCmAS27uNc0nVR2IIovzlacO838wX4=,tag:sSUqqkWUK2U65hgiRNNl6w==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SFE3K1JySzc1RzNoNS9K
        alpaMjVFWFZCNXBYeWo1VGZTZDhJak5IZHlzClZvY0FNandjcTY1U1orclF2N3lh
        bzFFbSszTHlUdExoamZnWG1kTFZLTGcKLS0tIFJJRlZWR3d2eGY1N0NHNVhhSnVI
        M1dpRkNGL2FqV0U5dUcxOXI4Y21PUjgKD4+lFoaYR+zHNXuBvxyUW7quwP/gY/K/
        TaEKOSueUMnDrrvDAdgdCbIS+jPIKoEs3682sqnZVujxD5ixCgyPqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T16:13:21Z"
  mac: ENC[AES256_GCM,data:SB9qOJoaGN6Hm4pNx4TxGvhJNbBRUYwmknXKkKY1SaVAyDuYes0c1dhlZdP/Zz4Atv9sQrZlUutq2NY1ZJy+UjiuPOICy2RdADFZu+vkFrHdOUzuDVcPSj5Vxccb/gdn4N7WilUA7zu/V5pA799fGOArzR85mSUMeUO/0XdiDRc=,iv:Ad/f8WHT3q2diU6YI/2+6cUKoDDqH4O9BMi4nHBHyNA=,tag:YCYGFyKtH78SUJJcsNjCYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
