apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:A0lC3Xvo/Q2IpnAVa7F1X91Lr33OOMfpA5xBW5Lg+PAf1Ii6KtG4d/xKL3HRBWzaOwNjG85Nv8l1i9gh/Vi79b55jzYSMOH29RQUpThyQC95t9+iwgQrwxqp6DqvSPbDu55nzanvxHCQ9/HEJHuUnpBqx9dCNbgVWzF72CuQo4UgTpwV2OJHhNTT/vi78lRrEE9auUjKkgnHULkKjtVuaaFKEL/DhQ/1EOwUtLTSQlENtHgQ,iv:joZczrGiut5zVFr18vukcCnn6UgBMn81dahsFMGcF7U=,tag:dXssD3i+feSjIos6jqk7kg==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQUExSXFCSTA5MDE1MVVH
        WmZlMWVUNzVQcFE4ZDdYczVCdU50UCtnK2lRCktEV3BGMVJZdUZJcVRZdExVY2pr
        b1BmQUpsZVNTZ2pXSFhkaXRFMUs3VmcKLS0tIEp0ckJTaFZPTURsKzU5VWJFVS9k
        Sm9NY2hVTnZ6MEF6cTBWQ2ppS2VsZ0UKwzfLpGjKurd26lIVIx3wIbxDI43IPL24
        EVflvmOaxDhfsj4KbWYa7sPXyn3rHt9UsV5ZguDmmi3IXeW5XLEclA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T15:15:44Z"
  mac: ENC[AES256_GCM,data:ky8q5M9WJ+Am7APK27T4OZWSx0+CztAeYpJjrv4Jrqd24e3NABJ7ToSymE3XTrfbQ4pzvPg8e73oad2bJGg/bM/u7KTi0VG8oafRUmLB+d5ie+fJIpQu0gH7SeMmL85e/AzgNi+mFO+hWRdfImlad1Q3qWuToNdbmJd2kuRYsqM=,iv:8g0K5lrCo8KQjnU9yImYJ3c1wg7nJQWUexEjDhFMVGc=,tag:ZFLXf9wx88gmsY0kdbNkdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
