apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:BuY1/ot7Qixot6FsoJ4Tn6AiHCHcquI5tiL3iowd9WLJoOndmvsWxgQqNE6e3z1nvApvtaHZi0liaSAz+un6Zp0R29AP7nvQ6yuoeK2DmoY4rJy2i+TeSZ/Ujpqcqle8gvlEa/B6Bymy0ZTuRN2quXBcDkNWQkeOIQgyNR9wLW7fQ4ooyNwULV9rQDIatbGJMnIVdTZexvcrs5V2xjTnA9L1afj9rkl0ec0nZiRG0+XI9YKM,iv:qUzKCKelWXYgNKVVWPDwu3ltpiSb8U/7/nYjSx9zfX0=,tag:ZScQ16WQY1pyiiuAlAWBfw==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RFJDSmRvQlZOMHd4c3Av
        YTNxTjkwS0NNbXRZVmZQdWhvVmE0RU84TXlzCi9SUk43K3hpVDRINTZzZHBEc0No
        aVpWbkVKamVBUkZDNTRtNjd2bWFHd2cKLS0tIEQ5SXRyUUVKZkhJbWtOMXRtQkFv
        WlVYU2RpV2orcTZBbzNCeXhQREluSEkKbG1YJdBs1XkVATm84UgtIO2CxBNooZOy
        xjBBexS13Ro3ujIWDu3yRcWnduUcSljY7AV9fs6sDbBWfBWF2Pzhiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T15:11:58Z"
  mac: ENC[AES256_GCM,data:AJ3BkZ0pe+XVjTnX4Y53LxhAoKmfP65wIFnBqkiV9cpGvio5fOxx9tvbWIo8+vge9zS2DWXdCSCln5gJavm+i1+gvU3pm6b0BEV+mhPMKb9wS8wU0D1Z9sE1RM8K+jDXMHGLBZ5Cr9ZHFXbfmGqV8/t+Jp189YHAdy94qfsxZb8=,iv:MNDtIwXQhxwjw64aXnDaMtmrIBpYhSm2nsE10KuCdUo=,tag:weIKaGfdtNvY4cn3bPEFEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
