---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security

resources:
  - ./namespace.yaml
  - ./external-secrets
  - ./authentik
# External secrets should be implemented.
# Most popular is 1password, but it's paid
# https://github.com/tholinka/home-ops implements secrets via bitwarden (which is free)

components:
  - ../../components/common
