apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BAsLRYclE9DY3fNxpUWxMYXw7K0JrU5ZMEo4zPo5QmBMHj5OWXbJbQ==,iv:MGkHIYGTL+QcnXF+9OmcB6hb1aPuUKAJVVZjqk+ZNdk=,tag:p6OLD3MTaFEWjLg8SCcTTg==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdVB2SHZBUVVJVm1SME14
        aU1IT3NGSWpxaHFUY3QvTmdhSWh2NStTVW5vClF1SkNsWHlrcVZtM3Zxb1RtSlMv
        bVlWUnNJR3ZUc1c3dGdvZk5mVVh2WVEKLS0tIHVoYWVJWGxwQmlKL292ZElaZ1Z4
        RGZqUzhFQ0dCYWt0dWpOK29oVFdoQncKfzgPQ5czqmyeiiSQPbiZIw7rB4pMSxuJ
        lYfaA6Du3YRnI2YR+DNeBopXvMDjCuHguwnPW4NiBfH1dBRD3H1NkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T15:15:44Z"
  mac: ENC[AES256_GCM,data:Rog9knerVJ2zVWvSyPn+4Y53DJx6zZKe93e6ZIQ9A9/x8+XhbpH+ipDGbESp+crDdr939ylxulWC9WoxKX2PFn4o7S0JnlG40mvvgJOqFGU32GghRIIAsaT3smwbg6uzR1yCcRVdB1AgRoxntl3NDXgtNmyliA6P3caojjtmgJ0=,iv:ZENyMY53aRgWDraVQhV+ILFX695iAZi+qAupT9+7FgI=,tag:7eEDS45XCZXqebEfPNSv6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
