apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:LdTzQmoLiDWQPkQBYH9Dd7Btvv5IAA7YBYNbcT0GIYm2FwfBQoF/xQ==,iv:2kW+tnmb45NznfAutoFeKIbhTDnpnhfIznIz/RJwXNo=,tag:AKCkTjfu8bfbSiItc/vMTA==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncEg3QlNCdXJvMlFvUVgx
        RU9jU2E1K3h5dlphWmN4R3VhdXBYaDhybFZFCjJuRjFoZ25RQU53RDhpeElTb1Ba
        RXVYdWFFVFlZT0JmOXRRc3JlWk9zdmcKLS0tIDhFSkJJcytTR1JIZlBIT2ZNZGJ6
        YWxtMWJrd3hUQlQ3dG04TlRWdy9VbzQKNcokkZu9wDTKM17sLcJ7OkafSI1nFhyO
        /IM1vRlkJh12vPFE4351skFkgDdExf4gRoZH9MzXdDSh5b/2YBl8Ig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T19:13:05Z"
  mac: ENC[AES256_GCM,data:Bka475PO/TH009Jq3AZbezkM5fLy/evFvsJoYm9fFpjpPM0s70FTDQxaNi3+SE+iYlyYN1a46yo38HPKlVVvM+d/Tn+G3CMqI4t0U4BFEle3SCjbaLSZjPpVvYC4mRsqhl9wYs29mEaQOeilETbvuug8QIV1ZJB+HH0NVWJONiM=,iv:LVo5qX/CngF1DOz7wtrYHPIKHtSHusGpTusrG5Ijbo8=,tag:Pafpdq9Zo2ItKCijhj/ynA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
