apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:t13V8NLUI0E4hr7Z6uQ1liYFg9zqvqk=,iv:5if5UZzzVMFv5XPAFph811GPv8CG+werjquIfV+s7DU=,tag:0mFJ9Wg14No7pzs/XQs6nQ==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZHJyWTA4azIvRVJIT2E5
        VmdBdVEvU0F5WVVPcEhoTllOKzZGakR5TkFzCnVBLzBQUzk2YlFGOFlUdVpLQ1p0
        Yy91WnUwNWpSL3lOWnBHejNRSXdyeFEKLS0tIDEvSmk0Q2dXODFQdTU0VTY2RVJC
        TTd5QSt5RDk3bisxdmZDcitVVzJ1SEkKpe8IRsNrlNZEr40HULJc54S2IetE9zGN
        cHWW7OhKqNOzryGFgQzlSz6CcJx0dtF57AT+URPFTJ2220YPkEdZLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T15:11:58Z"
  mac: ENC[AES256_GCM,data:EdGaHtdrRF92JZf2zVph9nUbA0juqvEP48B63HBuAuC8YbnjKLpn1aTqUmEKt2CZQvtXbZ00TAP10TXy/mF3LBY+3dKAo8VMaUVzlqFZzIXmQhks4vWaEJ+F41K+Hz2rGXdei+DT1hnyehDjW5k0koeNeDLC1CDNaQquPg58WeA=,iv:aAXfbAWo9sXsFrrRqS4zyipN2PUI0HKVOHuMJ68cgSI=,tag:xBAFOOInnEklMuRtbZpQjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
