apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:xdBpjIzUgPbizxsRuPEIG4Yt8c64fY3NCmGZyJxe9XYoUIII41ES+g==,iv:7k+0DSiv/V8iyqSr7l70tszSAVX456P9kgqoGoG85YI=,tag:iy2txSzIna/HCIkD2INQ4w==,type:str]
sops:
  age:
    - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R0RwLzc2ai9jODlkWUFG
        RXFMamEwbGFlZlNZbklVbmxzWm5OSjFIVW5nCjNJZHFIbEo2MmU1WmtmL2o1Ylls
        dVduZXVaald0K0lWNkl6UkhCZ1hZZUEKLS0tIGlEa1ZFdlIvejlxbzRNcjBweW5n
        MHpuc3lxY0tIWk04WHVYWmswVEkxWFEKsKed/DElYzkxC9lTQtSWHxxD75NAYhVq
        ZIUsrMQarg2LhjMaDFOBXTfZ1vJ88OyIaDp0uNwisg8VfNCuIMEq4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-07T16:13:21Z"
  mac: ENC[AES256_GCM,data:AGYpCxN0bxcV6BDIEBm8pfgRnJAq0h7C5LM1z5uqVXGXvkriDQitfcGhR8Mych6GsU8qlDWAGkBV8UymDJ0G2DVEevr7zaPRZSzWp7YuGlLZpq5wFFTBncukKmLYA4/ekqQJFpay7vn3A3xCl9yIYDgAU+PvVrRW8hZ5xINKSDM=,iv:zmHe6XDPImYl3UZlcv77a7HORIrwmaC7ew3swQp34As=,tag:Zwo+uDhDZyncpR7rhYJDzA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
