---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.50.100:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.50.100"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "blade-cm4-001"
    ipAddress: "10.0.50.7"
    installDiskSelector:
      serial: "0x0f750869"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ee21ef4a5ef808a9b7484cc0dda0f25075021691c8c09a276591eedb638ea1f9
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "dc:a6:32:a6:75:ba"
        dhcp: false
        addresses:
          - "10.0.50.7/24"
        routes:
          - gateway: "10.0.50.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.0.50.100"
  - hostname: "esxi-2cu-8g-02"
    ipAddress: "10.0.0.145"
    installDiskSelector:
      serial: "Virtual disk"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "34:97:87:58:7b:00"
        dhcp: false
        addresses:
          - "10.0.0.145/24"
        routes:
          - gateway: "10.0.50.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.0.50.100"
  - hostname: "esxi-2cu-8g-01"
    ipAddress: "10.0.0.146"
    installDiskSelector:
      serial: "Virtual disk"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "34:97:87:58:7b:01"
        dhcp: false
        addresses:
          - "10.0.0.146/24"
        routes:
          - gateway: "10.0.50.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.0.50.100"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

