---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/sops
  - ../../components/repos/app-template

resources:
  - ./namespace.yaml
  - ./headlamp
  - ./grafana
  #- ./kube-prometheus-stack
