---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: &name bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.eu
      identityURL: https://identity.bitwarden.eu
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: BITWARDEN_MACHINE_KEY
            name: *name
            namespace: &namespace security
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: *namespace
        key: ca.crt
      organizationID: ${BITWARDEN_ORGANIZATION_ID}
      projectID: ${BITWARDEN_PROJECT_ID}
