apiVersion: v1
kind: Secret
metadata:
    name: bitwarden
    namespace: security
type: Opaque
stringData:
    BITWARDEN_MACHINE_KEY: ENC[AES256_GCM,data:8dw8B+Jqvijes3trBLXTiH9cug3B7g6bkF0QjGxIx6k+AnSVPqbEaIWPm/58x5xNA9slPFRRAvzm3VeUxI93gajU/YtClOc+FtfFz8g3lJoqa54c3Acuz8DFk/3Y6A==,iv:tvOt5ZCWblNsMMCIbGyKjxGU3diW/i0vZt/Jj7dqbmY=,tag:JGPNAmNP4R+ACiMBpA6MJQ==,type:str]
    BITWARDEN_ORGANIZATION_ID: ENC[AES256_GCM,data:nlXq4PWGx2IGgvIbZUECdir4iBvC8mh7RoBGoEa/kSQbKj7w,iv:+drVfMtz+skqwLqIEVBdGaR0+5qScztQ/pgSEdOw71o=,tag:DJYyW+5jUxUJ3Qmc2xwp6g==,type:str]
    BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:i32ozffbo4le+8iXAwR7s1TfvKbYER90fgVVDuHrCa+nPjiJ,iv:zJ31BMI0fPP5HV6hzgkydn2xrbFZeV34vBeP9kNMU3Y=,tag:UGk25u/Wi1y+4X02f0tP5g==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncEg3QlNCdXJvMlFvUVgx
            RU9jU2E1K3h5dlphWmN4R3VhdXBYaDhybFZFCjJuRjFoZ25RQU53RDhpeElTb1Ba
            RXVYdWFFVFlZT0JmOXRRc3JlWk9zdmcKLS0tIDhFSkJJcytTR1JIZlBIT2ZNZGJ6
            YWxtMWJrd3hUQlQ3dG04TlRWdy9VbzQKNcokkZu9wDTKM17sLcJ7OkafSI1nFhyO
            /IM1vRlkJh12vPFE4351skFkgDdExf4gRoZH9MzXdDSh5b/2YBl8Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T22:20:17Z"
    mac: ENC[AES256_GCM,data:0rEdJu/XDsmegPay9fVFEjt4ZIByIlyS3SNGGOJQhm4SASoL5xOOqfM6F+v+Cyz3UPUpqYO7Z8kgyDDXIbyXYG18sD4gryxLvJ3t19jaiJSQJBK2RAwUXVlKQ5K40EvM3WQ9+AKJCc+is7fbuazhuSf9RU/pGAWFeC7nhtejGQs=,iv:fKVFs/anjDSZrJPhnM1fitHBAuLY4VUBI/7OVca9sLk=,tag:ZtkbEYhKyBPnlWJxNwyZ6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
