apiVersion: v1
kind: Secret
metadata:
    name: bitwarden
    namespace: security
type: Opaque
stringData:
    BITWARDEN_ORGANIZATION_ID: ENC[AES256_GCM,data:nlXq4PWGx2IGgvIbZUECdir4iBvC8mh7RoBGoEa/kSQbKj7w,iv:+drVfMtz+skqwLqIEVBdGaR0+5qScztQ/pgSEdOw71o=,tag:DJYyW+5jUxUJ3Qmc2xwp6g==,type:str]
    BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:raUDBr4z5NYGIzI5FgGFVUXdx7TlzwUyhlmBimXbZA+TUyE=,iv:f9z/TCYFxcwNiD3c6CWjecDQ0L3G/PKhIpesQWhAmag=,tag:YXpkr/KYGnYbgClbORMr5w==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncEg3QlNCdXJvMlFvUVgx
            RU9jU2E1K3h5dlphWmN4R3VhdXBYaDhybFZFCjJuRjFoZ25RQU53RDhpeElTb1Ba
            RXVYdWFFVFlZT0JmOXRRc3JlWk9zdmcKLS0tIDhFSkJJcytTR1JIZlBIT2ZNZGJ6
            YWxtMWJrd3hUQlQ3dG04TlRWdy9VbzQKNcokkZu9wDTKM17sLcJ7OkafSI1nFhyO
            /IM1vRlkJh12vPFE4351skFkgDdExf4gRoZH9MzXdDSh5b/2YBl8Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T14:03:20Z"
    mac: ENC[AES256_GCM,data:nntQMumjUwLDgjIq2IypL5ci+2wG25gZh55MkbnISYF+qhPaiPC6GT6Hrk4wf1IT6EhwzKU7KriKqUhT88X9QFx3i6QbSb4eXADQTPCyfh9No2AAGxZRfBfYPy8FNnG64q6WPycaBRngQwHTPZ0YsSAhP87EVVyq8xE5vLGSDlY=,iv:fR8rzOYRHeFDIc8gFFPVtIoK7Or9sqgg/JLUJ76ojJ0=,tag:gVtUJcgcq+0/L7n2QdbmaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
