apiVersion: v1
kind: Secret
metadata:
    name: bitwarden
    namespace: security
type: Opaque
stringData:
    BITWARDEN_MACHINE_KEY: ENC[AES256_GCM,data:8dw8B+Jqvijes3trBLXTiH9cug3B7g6bkF0QjGxIx6k+AnSVPqbEaIWPm/58x5xNA9slPFRRAvzm3VeUxI93gajU/YtClOc+FtfFz8g3lJoqa54c3Acuz8DFk/3Y6A==,iv:tvOt5ZCWblNsMMCIbGyKjxGU3diW/i0vZt/Jj7dqbmY=,tag:JGPNAmNP4R+ACiMBpA6MJQ==,type:str]
    BITWARDEN_ORGANIZATION_ID: ENC[AES256_GCM,data:nlXq4PWGx2IGgvIbZUECdir4iBvC8mh7RoBGoEa/kSQbKj7w,iv:+drVfMtz+skqwLqIEVBdGaR0+5qScztQ/pgSEdOw71o=,tag:DJYyW+5jUxUJ3Qmc2xwp6g==,type:str]
    BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:raUDBr4z5NYGIzI5FgGFVUXdx7TlzwUyhlmBimXbZA+TUyE=,iv:f9z/TCYFxcwNiD3c6CWjecDQ0L3G/PKhIpesQWhAmag=,tag:YXpkr/KYGnYbgClbORMr5w==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncEg3QlNCdXJvMlFvUVgx
            RU9jU2E1K3h5dlphWmN4R3VhdXBYaDhybFZFCjJuRjFoZ25RQU53RDhpeElTb1Ba
            RXVYdWFFVFlZT0JmOXRRc3JlWk9zdmcKLS0tIDhFSkJJcytTR1JIZlBIT2ZNZGJ6
            YWxtMWJrd3hUQlQ3dG04TlRWdy9VbzQKNcokkZu9wDTKM17sLcJ7OkafSI1nFhyO
            /IM1vRlkJh12vPFE4351skFkgDdExf4gRoZH9MzXdDSh5b/2YBl8Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T15:29:07Z"
    mac: ENC[AES256_GCM,data:vHKFCziNqBrFKgMx3wVHrP6zZTA56DIiGSaISDyinFSRwSUg5gGSt/9edrAB9+uGRA01TSFQGkJl4PuaHBH43ogTn4uA8jjiWV8NmpNuciSQBbwAMBbZ0C37Sw5ITzeUuvjqTj+L+tGRFVRKgzNEYKXVFvB/RvOfYYiK/Bl5V+I=,iv:cIqzNpd0I6HMWZ2/ITypVUDNgtWl1rdGPIFvpueILXg=,tag:HOAk4v8bShNV4NsGS4NgMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
