---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
  - path: patch-statefulset.yaml
    target:
      kind: StatefulSet
  - path: patch-helmrelease.yaml
    target:
      kind: HelmRelease
