apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
stringData:
    api-token: ENC[AES256_GCM,data:Q/EO1flnXjhh/GuaFMufV4T6a6X6+slo1g==,iv:YsQmkJ6VRkmAWya6Fmlt6YUW/yX3DTqZOS6Z2c8+WwA=,tag:hAUOIr8hDFRRHYeXyxvhpg==,type:str]
    password: ENC[AES256_GCM,data:ZzUeCQspj78JwUkvCkGitFC0FtNiGJdQrw==,iv:2Gy+4GmsR7B3mbtoDhldGjPAmBLXTIZG8bxxUI9Qo5M=,tag:avXs9ZKX+FlpvbooFjU6kQ==,type:str]
sops:
    age:
        - recipient: age1yzrqhl9dk8ljswpmzsqme3enad5kxxhsptdvecy3lwlq0ms80gaqxrctst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncEg3QlNCdXJvMlFvUVgx
            RU9jU2E1K3h5dlphWmN4R3VhdXBYaDhybFZFCjJuRjFoZ25RQU53RDhpeElTb1Ba
            RXVYdWFFVFlZT0JmOXRRc3JlWk9zdmcKLS0tIDhFSkJJcytTR1JIZlBIT2ZNZGJ6
            YWxtMWJrd3hUQlQ3dG04TlRWdy9VbzQKNcokkZu9wDTKM17sLcJ7OkafSI1nFhyO
            /IM1vRlkJh12vPFE4351skFkgDdExf4gRoZH9MzXdDSh5b/2YBl8Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T17:19:55Z"
    mac: ENC[AES256_GCM,data:6Dhr+JA9L+N8Hsc9HzXB48kwKRRH+oSjEOpeRNrBU7bXURvoMut+60ao6tm7m4sjUl5EQ4UuKz7G6BQmfEOF2Rz3yWB3REkHu2zQqYrAp8xcIdI8ZNlOWacMVV48HrIuozQSzYuBVXz7lkMddNlCvQv017LuWhCAG9VHoPLeCpY=,iv:oo6LUOLy2k9ugD3CM0q864DY6Mwz7u+fMZ67xadZu5k=,tag:r689YVdDl0GFVdugU9DRdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
